version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie_catalog
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    container_name: laravel_app
    volumes:
      - ./server:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: docker/Dockerfile
    container_name: vue_client
    volumes:
      - ./client:/app
    ports:
      - "5173:5173"
    networks:
      - app-network
    command: sh -c "npm install && npm run dev"

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: